name: NodeJS CI

on:
    push:
        branches: [ "pipelines", "master" ]
    pull_request:
        branches: [ "pipelines", "master" ]

jobs:


    format:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - name: Checkout to ${{ github.head_ref }}
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            
            - run: npm ci
            - run: npm run format

            - name: Commit changes to ${{ github.head_ref }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Apply formatting changes
                branch: ${{ github.head_ref }}

    lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm ci

            - name: Lint
              run: |
                  npx eslint .
    

    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: |
                npm install
            # idk actually what to put into build
            
